/**
 * Blocklist các disposable/temporary email domains.
 * Nguồn: github.com/disposable-email-domains/disposable-email-domains
 * Update định kỳ hoặc khi thấy domain mới.
 */

const DISPOSABLE_DOMAINS = new Set([
  // Vietnamese temp emails
  "tempmail.vn",
  "mailvn.net",
  "emailvn.net",
  "maildrop.cc",

  // Common disposable domains
  "10minutemail.com",
  "10minutemail.net",
  "guerrillamail.com",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.de",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinater.com",
  "mailinator2.com",
  "throwawaymail.com",
  "throwaway.email",
  "fakeinbox.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.org",
  "getnada.com",
  "nada.email",
  "temp-mail.org",
  "tempail.com",
  "tempmail.com",
  "tempmailo.com",
  "fakemailgenerator.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "dispostable.com",
  "mailnesia.com",
  "maildrop.cc",
  "mintemail.com",
  "spambox.us",
  "spamgourmet.com",
  "mytrashmail.com",
  "jetable.org",
  "trash-mail.com",
  "spam4.me",
  "mailcatch.com",
  "emkei.cz",
  "anonbox.net",
  "mailsac.com",
  "dropmail.me",
  "mohmal.com",
  "tempinbox.com",
  "burnermail.io",
  "mail.bcbits.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "spam.su",
  "tempemailco.com",
  "tempemail.com",
  "emailondeck.com",
  "mytemp.email",
  "crazymailing.com",
  "inboxkitten.com",
  "mail临时邮箱.com",
  "tempr.email",
  "disposablemail.com",
  "instantemailaddress.com",
  "mailforspam.com",
  "meltmail.com",
  "sprarkpost.com",
  "mailtemp.net",
  "tempemailaddress.com",
  "tempmailaddress.com",
  "emailtemporal.org",
  "emailfake.com",
  "fakeinbox.org",
  "spamfree24.org",
  "spammotel.com",
  "sogetthis.com",
  "mailin8r.com",
  "mailinator.co.uk",
  "soodo.com",
  "tempmailbox.net",
  "meltmail.net",
  "inboxalias.com",
  "jetable.net",
  "nomail.xl.cx",
  "nomail2me.com",
  "mycleaninbox.net",
  "mailnator.com",
  "suremail.info",
  "tempinbox.xyz",
  "tmpmail.org",
  "tmpmail.net",
  "tmpmail.com",
  "emailage.cf",
  "emailage.ga",
  "emailage.gq",
  "emailage.ml",
  "emailage.tk",
  "tempomail.fr",
  "moakt.com",
  "moakt.ws",
  "emailwarden.com",
  "deadaddress.com",
  "mailforspam.net",
  "tempemail.biz",
  "tmpmail.biz",
  "tmpmail.info",
  "tmpmail.net",
  "tmpmail.org",
  "tmpmail.us",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "trash2009.com",
  "trashemail.de",
  "mytrashmail.com",
  "mailmetrash.com",
  "mt2009.com",
  "mt2014.com",
  "thankyou2010.com",
  "trash-mail.at",
  "trash-mail.de",
  "trashmail.at",
  "trashmail.me",
  "trashmail.org",
  "wegwerf-email.de",
  "wegwerfmail.info",
  "wegwerfmail.de",
  "wegwerfmail.eu",
  "wegwerfmail.org",
  "temp-mail.de",
  "temp-mail.ru",
  "fakeinbox.com",
  "inboxalias.com",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "deadfake.cf",
  "deadfake.ga",
  "deadfake.gq",
  "deadfake.ml",
  "deadfake.tk",
]);

/**
 * Check if email domain is a disposable/temporary email provider.
 * @param {string} email
 * @returns {boolean} true = blocked (disposable)
 */
export function isDisposableEmail(email) {
  if (!email || typeof email !== "string") return false;
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}

/**
 * Extract domain from email.
 * @param {string} email
 * @returns {string|null}
 */
export function getEmailDomain(email) {
  if (!email || typeof email !== "string") return null;
  return email.split("@")[1]?.toLowerCase() || null;
}
